package org.angzhao.demo.service.user.dal.mapper;

import java.util.List;
import org.angzhao.demo.service.user.dal.domain.CpAdminInfo;
import org.angzhao.demo.service.user.dal.domain.CpAdminInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CpAdminInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_admin_info
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    long countByExample(CpAdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_admin_info
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    int deleteByExample(CpAdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_admin_info
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    int insert(CpAdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_admin_info
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    int insertSelective(CpAdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_admin_info
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    List<CpAdminInfo> selectByExampleWithRowbounds(CpAdminInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_admin_info
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    List<CpAdminInfo> selectByExample(CpAdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_admin_info
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") CpAdminInfo record, @Param("example") CpAdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_admin_info
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    int updateByExample(@Param("record") CpAdminInfo record, @Param("example") CpAdminInfoExample example);
}