package org.angzhao.demo.service.user.dal.mapper;

import java.util.List;
import org.angzhao.demo.service.user.dal.domain.CpClassInfo;
import org.angzhao.demo.service.user.dal.domain.CpClassInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CpClassInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    long countByExample(CpClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int deleteByExample(CpClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int insert(CpClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int insertSelective(CpClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    List<CpClassInfo> selectByExampleWithRowbounds(CpClassInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    List<CpClassInfo> selectByExample(CpClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") CpClassInfo record, @Param("example") CpClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int updateByExample(@Param("record") CpClassInfo record, @Param("example") CpClassInfoExample example);
}