package org.angzhao.demo.service.user.dal.mapper;

import java.util.List;
import org.angzhao.demo.service.user.dal.domain.CpTeacherInfo;
import org.angzhao.demo.service.user.dal.domain.CpTeacherInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CpTeacherInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_teacher_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    long countByExample(CpTeacherInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_teacher_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int deleteByExample(CpTeacherInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_teacher_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int insert(CpTeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_teacher_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int insertSelective(CpTeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_teacher_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    List<CpTeacherInfo> selectByExampleWithRowbounds(CpTeacherInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_teacher_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    List<CpTeacherInfo> selectByExample(CpTeacherInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_teacher_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") CpTeacherInfo record, @Param("example") CpTeacherInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_teacher_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int updateByExample(@Param("record") CpTeacherInfo record, @Param("example") CpTeacherInfoExample example);
}