package org.angzhao.demo.service.user.dal.mapper;

import java.util.List;
import org.angzhao.demo.service.user.dal.domain.CpUserInfo;
import org.angzhao.demo.service.user.dal.domain.CpUserInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CpUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    long countByExample(CpUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int deleteByExample(CpUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int insert(CpUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int insertSelective(CpUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    List<CpUserInfo> selectByExampleWithRowbounds(CpUserInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    List<CpUserInfo> selectByExample(CpUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") CpUserInfo record, @Param("example") CpUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int updateByExample(@Param("record") CpUserInfo record, @Param("example") CpUserInfoExample example);
}