package org.angzhao.demo.service.user.dal.mapper;

import java.util.List;
import org.angzhao.demo.service.user.dal.domain.CpUserClassInfo;
import org.angzhao.demo.service.user.dal.domain.CpUserClassInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CpUserClassInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    long countByExample(CpUserClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int deleteByExample(CpUserClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int insert(CpUserClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int insertSelective(CpUserClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    List<CpUserClassInfo> selectByExampleWithRowbounds(CpUserClassInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    List<CpUserClassInfo> selectByExample(CpUserClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") CpUserClassInfo record, @Param("example") CpUserClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    int updateByExample(@Param("record") CpUserClassInfo record, @Param("example") CpUserClassInfoExample example);
}