package org.angzhao.demo.service.user.dal.domain;

import java.io.Serializable;

public class CpAdminInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_admin_info.admin_id
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_admin_info.admin_name
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_admin_info.admin_password
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    private String adminPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cp_admin_info
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_admin_info.admin_id
     *
     * @return the value of cp_admin_info.admin_id
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_admin_info.admin_id
     *
     * @param adminId the value for cp_admin_info.admin_id
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_admin_info.admin_name
     *
     * @return the value of cp_admin_info.admin_name
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_admin_info.admin_name
     *
     * @param adminName the value for cp_admin_info.admin_name
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_admin_info.admin_password
     *
     * @return the value of cp_admin_info.admin_password
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_admin_info.admin_password
     *
     * @param adminPassword the value for cp_admin_info.admin_password
     *
     * @mbg.generated Tue Apr 07 22:25:09 CST 2020
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }
}