package org.angzhao.demo.service.user.dal.domain;

import java.io.Serializable;

public class CpUserClassInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user_class_info.id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user_class_info.user_id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user_class_info.class_id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cp_user_class_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user_class_info.id
     *
     * @return the value of cp_user_class_info.id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_user_class_info.id
     *
     * @param id the value for cp_user_class_info.id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user_class_info.user_id
     *
     * @return the value of cp_user_class_info.user_id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_user_class_info.user_id
     *
     * @param userId the value for cp_user_class_info.user_id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user_class_info.class_id
     *
     * @return the value of cp_user_class_info.class_id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_user_class_info.class_id
     *
     * @param classId the value for cp_user_class_info.class_id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
}