package org.angzhao.demo.service.user.dal.domain;

import java.io.Serializable;

public class CpUserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user_info.user_id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user_info.user_name
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user_info.password
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user_info.nick_name
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cp_user_info
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user_info.user_id
     *
     * @return the value of cp_user_info.user_id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_user_info.user_id
     *
     * @param userId the value for cp_user_info.user_id
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user_info.user_name
     *
     * @return the value of cp_user_info.user_name
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_user_info.user_name
     *
     * @param userName the value for cp_user_info.user_name
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user_info.password
     *
     * @return the value of cp_user_info.password
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_user_info.password
     *
     * @param password the value for cp_user_info.password
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user_info.nick_name
     *
     * @return the value of cp_user_info.nick_name
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_user_info.nick_name
     *
     * @param nickName the value for cp_user_info.nick_name
     *
     * @mbg.generated Sat Mar 07 19:12:55 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }
}